import { SOVR_IR } from '../ir/types.js';
import { sha256 } from '../utils/hash.js';

export interface GeneratedFile {
  path: string;
  content: string;
  sha256: string;
  sourceRefs: string[];
}

const HEADER = (version: string, protocolVersion: string, sources: string[], hash: string) => `// ============================================================
// SOVR GENERATED FILE — DO NOT EDIT MANUALLY
// Compiler: @sovr/compiler v${version}
// Protocol: SOVR Financial OS v${protocolVersion}
// Source: ${sources.join(', ')}
// Hash: ${hash}
// ============================================================
//
// This file is a compiled product of the SOVR Protocol
// Specification. Manual edits will be overwritten on
// next compilation.
//
// To modify this file, edit the source specification
// and recompile. Do NOT edit this file directly.
// ============================================================

`;

export function generateTypes(ir: SOVR_IR): GeneratedFile[] {
  const files: GeneratedFile[] = [];
  const protocolVersion = ir.meta.protocolVersion;
  const compilerVersion = ir.meta.compilerVersion;

  // Group entities by domain
  const entitiesByDomain = new Map<string, any[]>();
  for (const node of ir.nodes) {
    if (node.type === 'entity') {
      const domain = (node as any).domain;
      if (!entitiesByDomain.has(domain)) entitiesByDomain.set(domain, []);
      entitiesByDomain.get(domain)!.push(node);
    }
  }

  for (const [domain, entities] of entitiesByDomain) {
    const lines: string[] = [];
    lines.push(`// Domain: ${domain}`);
    lines.push(`// Generated from SOVR IR with ${entities.length} entities`);
    lines.push('');
    for (const ent of entities) {
      const name = (ent as any).entityName;
      const pascal = toPascal(name);
      const attrs = (ent as any).attributes || {};
      lines.push(`export interface I${pascal} {`);
      for (const [attrName, attrDef] of Object.entries(attrs as any)) {
        const def = attrDef as any;
        const tsType = mapToTSType(def.type, def);
        const optional = def.required === false ? '?' : '';
        lines.push(`  ${toCamel(attrName)}${optional}: ${tsType}; // ${def.description || def.type}${def.format ? ` format:${def.format}` : ''}`);
      }
      lines.push('}');
      lines.push('');
      lines.push(`export type ${pascal}Id = string; // UUID branded`);
      lines.push('');
    }
    const contentBody = lines.join('\n');
    const hash = sha256(contentBody);
    const header = HEADER(compilerVersion, protocolVersion, [`02_domain-model.yaml:${domain}`], hash);
    const full = header + contentBody;
    const finalHash = sha256(full);
    files.push({
      path: `src/types/${domain}/${domain}.types.ts`,
      content: full,
      sha256: finalHash,
      sourceRefs: entities.map(e=>e.sourceRef),
    });
  }

  // Commands
  const commandsByDomain = new Map<string, any[]>();
  for (const node of ir.nodes) {
    if (node.type === 'command') {
      const domain = (node as any).domain;
      if (!commandsByDomain.has(domain)) commandsByDomain.set(domain, []);
      commandsByDomain.get(domain)!.push(node);
    }
  }
  for (const [domain, cmds] of commandsByDomain) {
    const lines: string[] = [];
    lines.push(`// Domain: ${domain} — Commands`);
    lines.push(`import { z } from 'zod';`);
    lines.push('');
    for (const cmd of cmds) {
      const fullName = cmd.sourceRef;
      const className = toPascal(fullName.replace(/\./g, '_')) + 'Command';
      const payload = (cmd as any).requiredPayload || [];
      lines.push(`export class ${className} {`);
      lines.push(`  static readonly commandName = '${fullName}' as const;`);
      lines.push(`  static readonly capability = '${(cmd as any).capability}' as const;`);
      lines.push(`  static readonly version = '${cmd.version}' as const;`);
      lines.push(`  constructor(public readonly payload: {`);
      for (const p of payload) {
        if (typeof p === 'string') {
          lines.push(`    ${toCamel(p)}: unknown;`);
        } else if (typeof p === 'object') {
          for (const [k,v] of Object.entries(p)) {
            lines.push(`    ${toCamel(k)}: unknown; // ${JSON.stringify(v).slice(0,80)}`);
          }
        }
      }
      lines.push(`  }, public readonly meta: { commandId: string; correlationId: string; causationId: string }) {}`);
      lines.push(`  get commandId() { return this.meta.commandId; }`);
      lines.push('}');
      lines.push('');
      // Zod schema stub for validation_library output
      lines.push(`export const ${className}Schema = z.object({`);
      for (const p of payload) {
        if (typeof p === 'string') lines.push(`  ${toCamel(p)}: z.unknown(),`);
      }
      lines.push('});');
      lines.push('');
    }
    const body = lines.join('\n');
    const h = sha256(body);
    const header = HEADER(compilerVersion, protocolVersion, [`03_command-catalog.yaml:${domain}`], h);
    const full = header + body;
    files.push({
      path: `src/commands/${domain}/${domain}.commands.ts`,
      content: full,
      sha256: sha256(full),
      sourceRefs: cmds.map(c=>c.sourceRef),
    });
  }

  // Events
  const eventsByDomain = new Map<string, any[]>();
  for (const node of ir.nodes) {
    if (node.type === 'event') {
      const domain = (node as any).domain;
      if (!eventsByDomain.has(domain)) eventsByDomain.set(domain, []);
      eventsByDomain.get(domain)!.push(node);
    }
  }
  for (const [domain, evs] of eventsByDomain) {
    const lines: string[] = [];
    lines.push(`// Domain: ${domain} — Events`);
    lines.push(`import { EventEnvelope } from '../../events/event-envelope.js';`);
    lines.push('');
    for (const ev of evs) {
      const fullName = ev.sourceRef;
      const className = toPascal(fullName.replace(/\./g, '_')) + 'Event';
      lines.push(`export class ${className} {`);
      lines.push(`  static readonly eventName = '${fullName}' as const;`);
      lines.push(`  static readonly aggregate = '${(ev as any).aggregate}' as const;`);
      lines.push(`  static create(envelope: EventEnvelope, payload: ${(ev as any).dataFields ? 'Record<string,unknown>' : 'any'}) {`);
      lines.push(`    return { envelope, eventName: this.eventName, payload, aggregate: this.aggregate, timestamp: new Date().toISOString() };`);
      lines.push(`  }`);
      lines.push('}');
      lines.push('');
    }
    const body = lines.join('\n');
    const h = sha256(body);
    const header = HEADER(compilerVersion, protocolVersion, [`04_event-catalog.yaml:${domain}`], h);
    const full = header + body;
    files.push({
      path: `src/events/${domain}/${domain}.events.ts`,
      content: full,
      sha256: sha256(full),
      sourceRefs: evs.map(e=>e.sourceRef),
    });
  }

  // Sort files deterministically by path (R2)
  files.sort((a,b)=>a.path.localeCompare(b.path));
  return files;
}

function toPascal(s: string): string {
  return s.replace(/(^|_)([a-z])/g, (_,__,c)=>c.toUpperCase()).replace(/[^a-zA-Z0-9]/g,'');
}
function toCamel(s: string): string {
  const p = toPascal(s);
  return p.charAt(0).toLowerCase()+p.slice(1);
}
function mapToTSType(yamlType: string, def: any): string {
  switch (yamlType) {
    case 'string': return def.format==='uuid' ? 'string /* uuid */' : 'string';
    case 'integer': return 'number';
    case 'decimal': return 'string /* decimal */';
    case 'boolean': return 'boolean';
    case 'timestamp': return 'string /* ISO8601 */';
    case 'date': return 'string /* date */';
    case 'enum': return def.values ? def.values.map((v:string)=>`'${v}'`).join(' | ') : 'string';
    case 'array': return 'unknown[]';
    case 'object': return 'Record<string, unknown>';
    default: return 'unknown';
  }
}
