{
  "domain": "amendment",
  "buildId": "2fc77ebc6fd7756f",
  "generatedAt": "2026-07-17T23:00:40.039Z",
  "artifacts": [
    {
      "file": "events/amendment-events.ts",
      "hash": "e8f1d7dbb369e26f"
    }
  ],
  "sourceHash": "1c31d219efa68943"
}