{
  "domain": "capability",
  "buildId": "2fc77ebc6fd7756f",
  "generatedAt": "2026-07-17T23:00:40.038Z",
  "artifacts": [
    {
      "file": "events/capability-events.ts",
      "hash": "b7045be3f558b008"
    }
  ],
  "sourceHash": "9e5e1704e4c2f764"
}