{
  "domain": "collateral",
  "buildId": "2fc77ebc6fd7756f",
  "generatedAt": "2026-07-17T23:00:40.035Z",
  "artifacts": [
    {
      "file": "events/collateral-events.ts",
      "hash": "50e778e9ce82f10a"
    }
  ],
  "sourceHash": "a1c3abe95049df02"
}