{
  "domain": "concurrency",
  "buildId": "2fc77ebc6fd7756f",
  "generatedAt": "2026-07-17T23:00:40.038Z",
  "artifacts": [
    {
      "file": "events/concurrency-events.ts",
      "hash": "9a9239fd7be55795"
    }
  ],
  "sourceHash": "a48f0139ae65a945"
}