{
  "domain": "custody",
  "buildId": "2fc77ebc6fd7756f",
  "generatedAt": "2026-07-17T23:00:40.035Z",
  "artifacts": [
    {
      "file": "events/custody-events.ts",
      "hash": "3328c0e7d7b07942"
    }
  ],
  "sourceHash": "531174e218afbcb6"
}