{
  "domain": "oversight",
  "buildId": "2fc77ebc6fd7756f",
  "generatedAt": "2026-07-17T23:00:40.039Z",
  "artifacts": [
    {
      "file": "events/oversight-events.ts",
      "hash": "e48c285684f14e8c"
    }
  ],
  "sourceHash": "44a7f9fe8443ba36"
}