{
  "domain": "override",
  "buildId": "2fc77ebc6fd7756f",
  "generatedAt": "2026-07-17T23:00:40.038Z",
  "artifacts": [
    {
      "file": "events/override-events.ts",
      "hash": "592e4ccbd9d168d4"
    }
  ],
  "sourceHash": "267c15f5a6131cda"
}