{
  "domain": "ownership",
  "buildId": "2fc77ebc6fd7756f",
  "generatedAt": "2026-07-17T23:00:40.036Z",
  "artifacts": [
    {
      "file": "events/ownership-events.ts",
      "hash": "a8baea5cb9d818b5"
    }
  ],
  "sourceHash": "d6bbd915eb933452"
}