{
  "domain": "policy_rule",
  "buildId": "2fc77ebc6fd7756f",
  "generatedAt": "2026-07-17T23:00:40.040Z",
  "artifacts": [
    {
      "file": "events/policy_rule-events.ts",
      "hash": "af597a357b94710f"
    }
  ],
  "sourceHash": "83e34149ff284a8f"
}