{
  "domain": "reconciliation",
  "buildId": "2fc77ebc6fd7756f",
  "generatedAt": "2026-07-17T23:00:40.036Z",
  "artifacts": [
    {
      "file": "events/reconciliation-events.ts",
      "hash": "e77cd8219ad341c3"
    }
  ],
  "sourceHash": "e41e8d4a93dedaa7"
}