{
  "domain": "registration",
  "buildId": "2fc77ebc6fd7756f",
  "generatedAt": "2026-07-17T23:00:40.038Z",
  "artifacts": [
    {
      "file": "events/registration-events.ts",
      "hash": "2f6bb235847053ad"
    }
  ],
  "sourceHash": "43021b97d20521b8"
}