{
  "domain": "request",
  "buildId": "2fc77ebc6fd7756f",
  "generatedAt": "2026-07-17T23:00:40.039Z",
  "artifacts": [
    {
      "file": "events/request-events.ts",
      "hash": "c2113d274e2579a2"
    }
  ],
  "sourceHash": "4d6eb2019c5bb94a"
}