{
  "domain": "reserve",
  "buildId": "2fc77ebc6fd7756f",
  "generatedAt": "2026-07-17T23:00:40.035Z",
  "artifacts": [
    {
      "file": "events/reserve-events.ts",
      "hash": "745c750e2f6448d2"
    }
  ],
  "sourceHash": "91fc06897dee11c2"
}