{
  "domain": "session",
  "buildId": "2fc77ebc6fd7756f",
  "generatedAt": "2026-07-17T23:00:40.037Z",
  "artifacts": [
    {
      "file": "events/session-events.ts",
      "hash": "f5c9c4ae3132fcf1"
    }
  ],
  "sourceHash": "f868cb8f2dadbcce"
}