{
  "domain": "validation",
  "buildId": "2fc77ebc6fd7756f",
  "generatedAt": "2026-07-17T23:00:40.038Z",
  "artifacts": [
    {
      "file": "events/validation-events.ts",
      "hash": "973c586b584636e9"
    }
  ],
  "sourceHash": "a2b87115bd1320b2"
}