{
  "domain": "valuation",
  "buildId": "2fc77ebc6fd7756f",
  "generatedAt": "2026-07-17T23:00:40.035Z",
  "artifacts": [
    {
      "file": "events/valuation-events.ts",
      "hash": "d77c8f481115093a"
    }
  ],
  "sourceHash": "e3f7c8677ebe7bae"
}