{
  "domain": "identity",
  "buildId": "5678ed61edbc97e3",
  "generatedAt": "1970-01-01T00:00:00.000Z",
  "artifacts": [
    {
      "file": "state-machines/identity-state-machine.ts",
      "hash": "568e75e45bc4e76a"
    },
    {
      "file": "commands/identity-commands.ts",
      "hash": "652bac689c354690"
    },
    {
      "file": "events/identity-events.ts",
      "hash": "c29969ab2f0db4b1"
    }
  ],
  "sourceHash": "5d4bc137aa395095"
}